### PR TITLE
Dont minify CSS in debug

### PR DESCRIPTION
**Pull request by reloxx13**
It should be "css" and not "minify" to disable minifying in debug mode.

### CODE REVIEW

**Comment by reloxx13** [comment]
@trentrichardson hope u r still active and can merge ;)

**Comment by trentrichardson** [comment]
It has been a little while since I've had my hands in this project. I applied your changes to the cakephp-v3.0 branch. I'd like to figure out why the tests are failing though before moving to the master branch.

**Comment by trentrichardson** [comment]
Ok, I've merged with master and tagged a new version.

**Comment by reloxx13** [comment]
thank you 👍

**Pull request closed without merging**
